### PR TITLE
Add images and refine Getting Started section.

### PR DESCRIPTION
**Pull request by videlanicolas**
### Checklist for this pull request

- [x] I have read the [guidelines for contributing](../CONTRIBUTING.md).
- [x] I have checked that my code additions did not fail tests.

### Description

This merge adds step by step images to better showcase how to install this addon.
Aside from installing it from AssetLib in Godot, the user must add `runtime.gd` as a singleton.
I'm also re-designing the sections to have them behave with sub-sections.
Since I'm using Visual Studio Code to do my coding, add .vscode to .gitignore, there are no project files to import there.

### CODE REVIEW

**Comment by ephread** [comment]
LGTM!

There's just a lack of padding _after_ the images in the generated documentation, but that's very minor, I don't know how/if it can be solved.

Screen Shot 2021-11-19 at 12 32 20

**Comment by videlanicolas** [comment]
Fixed, I added line separation between those images on [my fork PR #3](https://github.com/videlanicolas/inkgd/pull/3/commits/a22bb60c3bf6cda82cab75ee02a3434490297905).

**Comment by videlanicolas** [comment]
Adds to #41 .

**Comment by ephread** [comment]
@videlanicolas thanks for fixing the space issue. I forgot to ask, what's in your `.vscode` for this project? I use VS Code too on a regular basis and if I don't mind committing a configuration file if it's something that would benefit everybody and enforce some much-needed conventions.

**Comment by videlanicolas** [comment]
> what's in your .vscode for this project?

I use a restructuredText extension, and that has some settings to auto-render the view while working. This is found under `.vscode/settings.json`. Given that not everybody has this extension, and that the only file under `.vscode` is this one, I figured we can ignore it since it doesn't break any build.

The contents:
```
{
    "restructuredtext.confPath": "${workspaceFolder}/docs/source",
    "restructuredtext.builtDocumentationPath": "${workspaceFolder}/docs/build"
}
```

**Comment by ephread** [comment]
Alright, makes sense, thanks for the clarification. Merging now!

**Pull request merged**
