### PR TITLE
Godot 4

### PR DESCRIPTION
**Pull request by ephread**
This PR tracks the changes required to run inkgd in Godot 4. (Also see #55)

### Global

- [ ] Replace keywords by annotations (for instance `@tool` and `@onready`).
- [ ] Replace all function names that clash with protected keywords, such as `continue`, `assert` or `null`.
- [ ] Replace remaining spaces by tabs.
- [ ] Add the `super` keyword in front of unqualified `.` accesses.
- [ ] Replace `Reference` by `RefCounted`.
- [ ] Update the getter / setter syntax.
- [ ] Replace `Array.remove()` by `Array.remove_at()`

### Runtime

- [ ] Replace `JSON.parse()` logic by an instance of `JSON`.
- [ ] Update all `Variant.Type` enum values in InkUtils.

### Editor Plugin

- [ ] Update the syntax connecting signals (now `obj.funcA.connect(funcB)`).
- [ ] Rename `get_icon` to `get_theme_icon`.
- [ ] Update the argument order of `OS.execute`.
- [ ] Replace `PoolStringArray` by `PackedStringArray`.
- [ ] Replace `PackedScene.instance()` by `PackedScene.instantiate()`.
- [ ] Review and update all `LineEdit` connections.
- [ ] Remove `Label.add_font_override()` calls and use `Label.font` property instead.

### CODE REVIEW

**Comment by ephread** [comment]
This script might also be useful, although I wouldn't run it on the codebase as-is. https://gist.github.com/aaronfranke/79b424226475d277d0035b7835b09c5f

**Comment by Jummit** [comment]
I converted the entire project to Godot 4 using the built-in tool, and here are some things you have to look out for:

* FuncRefs and threads should use callables
* Match statements need static values, so some enums have to be made static variables
* Manually converting the setter/getters is a lot of work, maybe it should be automated in some way
* Cyclic references are still a problem sadly

**Comment by ephread** [comment]
@Jummit perfect, thanks for investigating this. Did you push the conversion somewhere? I'm really curious to see what it looks like and if it maintains member orders.

I still need to land a couple of things in `main` before starting the conversion. I want prevent the Godot 3.x and the Godot 4.x versions of inkgd from diverging too much, but it's pretty close to being done.

We should be able to start the migration soon.

**Comment by lunarcloud** [comment]
Seems that "minimum_size" was changed to "custom_minimum_size"

**Comment by Jummit** [comment]
> * Cyclic references are still a problem sadly

I currently have cyclic dependencies in scripts using class_name, so it seems like it's working!

**Comment by Jummit** [comment]
Gave this a shot again.

I removed the `get_class` functions and used the `is` operator in `is_ink_class`. This works, but a lot of code needs to be replaced to use class references instead of strings.

All the "imports" can be removed, as cyclic references are now possible.

Setters and getters are interesting, I think they work different than before. In 3.5 you could use the `.` syntax to use the getter, now it uses it by default. I think this is the main cause for issues at the moment.

Maybe I'll try again another time, but it's too tedious for me at the moment.

**Comment by ephread** [comment]
Closed in favour of #75.

**Pull request closed without merging**
